tasks:
  - init: |
      curl https://sh.rustup.rs/ -sSf | sh
      1
      source /workspace/.cargo/env
      rustup install nightly
      rustup install stable
      rustup target add wasm32-unknown-unknown --toolchain nightly